# version: '3'
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - '3006:3006'
#     depends_on:
#       - db
#     environment:
#       - DB_HOST=db
#       - DB_USER=your_db_user
#       - DB_PASSWORD=your_db_password
#       - DB_NAME=your_db_name
#     volumes:
#       - .:/usr/src/app
#     command: npm start

#   db:
#     image: postgres:14
#     environment:
#       POSTGRES_USER: your_db_user
#       POSTGRES_PASSWORD: your_db_password
#       POSTGRES_DB: your_db_name
#     volumes:
#       - ./second.sql:/docker-entrypoint-initdb.d/second.sql
#     ports:
#       - '5433:5432'

#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3006:3006'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_NAME=pokemon_db
      - BACKEND_PORT=3006
    volumes:
      - .:/usr/src/app
    command: npm run dev

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: pokemon_db
    volumes:
      - ./second.sql:/docker-entrypoint-initdb.d/second.sql
    ports:
      - '5433:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

