version: '3.8'

networks:
  mynetwork:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3006:3006'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - BACKEND_PORT=${BACKEND_PORT}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/usr/src/app
    command: npm run dev
    networks:
      - mynetwork

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5433:5432'
    networks:
      - mynetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      - mynetwork

volumes:
  pgdata:
